### ISSUE TITLE
Seperate country-code from phone input

### ISSUE THREAD

**Issue by ljukas** [KaiHotz/React-PhoneNr-Input#1]
I just tried the demo and autocomplete with tools such as dashlane will remove the countrycode. 
Maybe seperate the country code into a locked input so this cannot happen?

**Comment by KaiHotz** [comment]
Thanks, I’ll have a look at it

**Comment by KaiHotz** [comment]
I came to the decision not to separate the country code from the input field since it needs to be part of the phone number
