### ISSUE TITLE
Start with an initial value.

### ISSUE THREAD

**Issue by efleurine** [KaiHotz/React-PhoneNr-Input#2]
I am trying to pass an initial phone number to the component but it seems that it cannot receive an initial value.

I want to edit a phone number that was already in my database using this component but I cannot manage to do that.

thanks for any help or hint

**Comment by KaiHotz** [comment]
@efleurine Fixed, now you can pass the ```initialValue``` prop to pass an initial  Phone number.
You can find an example on the styleguide https://kaihotz.github.io/React-PhoneNr-Input/
